/*
 * Created on 15 mars 2006 By Gabriel DROMARD
 */
package net.dromard.common.properties;

import java.text.MessageFormat;
import java.util.MissingResourceException;

import net.dromard.common.util.StringHelper;

/**
 * This Extention of java.util.Properties manage 2 aspects:
 * <ul>
 * <li>
 * <h4>Links to others keys</h4>
 * <b>Exemple:</b>
 *
 * <pre>
 *    my.key=Hi ${user.key}, this is a mail generated by ${robot.name.key}.
 *    user.key=Frederic Dupont
 *    robot.name.key=Robot
 * </pre>
 *
 * So <code>System.out.println(prop.getProperty("my.key")); </code> will return :
 *
 * <pre>
 *    Hi Frederic Dupont, this is a mail generated by Robot.
 * </pre>
 *
 * </li>
 * <li>
 * <h4>Value inclusion at execution time</h4>
 * <b>Exemple:</b>
 *
 * <pre>
 *    my.key=Hi {0}, this is a mail generated by ${robot.name.key} at {1,date}.
 *    robot.name.key=Robot
 * </pre>
 *
 * So <code>System.out.println(prop.getFormatedProperty("my.key", new Object[] {"Frederic Dupont", new Date()})); </code> will return :
 *
 * <pre>
 *    Hi Frederic Dupont, this is a mail generated by Robot.
 * </pre>
 *
 * </li>
 * </ul>
 */
public class DynamicProperties extends AdvancedProperties {

    /** serial UID. */
    private static final long serialVersionUID = -181417557219172496L;

    /**
     * Default constructor.
     */
    public DynamicProperties() {
        super();
    }

    /**
     * Retrieve a property.
     * @see java.util.Properties#getProperty(java.lang.String)
     * @param key the property key.
     * @return The property value (if it exists)
     */
    @Override
    public final String getProperty(final String key) {
        return transform(super.getProperty(key));
    }

    /**
     * Retrieve a property value.
     * @param name The property name
     * @param defaultValue The default value to be used if no values has been found.
     * @return The property value
     */
    @Override
    public String getProperty(final String key, final String defaultValue) {
        String value = null;
        try {
            value = super.getProperty(key);
            if (value == null) {
                value = defaultValue;
            } else {
                value = transform(value);
            }
        } catch (MissingResourceException e) {
            value = defaultValue;
        }
        return value;
    }

    /**
     * Retrieve a property using a formatter.
     * @see java.util.Properties#getProperty(java.lang.String)
     * @see java.text.MessageFormat#format(java.lang.String, java.lang.Object[])
     * @param key       The property key.
     * @param arguments The MessageFormat arguments.
     * @return The property value formated.
     */
    @Override
    public final String getFormattedProperty(final String key, final Object[] arguments) {
        return MessageFormat.format(transform(super.getProperty(key)), arguments);
    }

    /**
     * It will assume that the key value contains several values separated by a '|'.
     * @param key The property key
     * @return An array of string corresponding to the pipe (|) separated strings.
     */
    public final String[] getPropertyAsArray(final String key) {
        String value = getProperty(key);
        if (value != null) {
            return StringHelper.split(value, "|");
        }
        return null;
    }

    /**
     * This method is in charge of retreiving values of internaly referenced keys.
     * @param propertyValue The propertyValue to be parsed and resolved.
     * @return The propertyValue with inner references to others keys resolved.
     */
    private String transform(final String propertyValue) {
        String result = propertyValue;
        if (propertyValue != null) {
            while (result.indexOf("$(") != -1) {
                String intermediateResult = result;
                for (Object element : keySet()) {
                    String key = element.toString();
                    String value = get(key).toString();
                    if (!propertyValue.equals(value)) {
                        result = StringHelper.replaceAll(result, "$(" + key.toString() + ")", value);
                    }
                }
                if (intermediateResult.equals(result)) {
                    return result;
                    //throw new Error("Properties value: '" + result + "' migth not point to a valid key.");
                }
            }
            while (result.indexOf("${") != -1) {
                String intermediateResult = result;
                for (Object element : keySet()) {
                    String key = element.toString();
                    String value = get(key).toString();
                    if (!propertyValue.equals(value)) {
                        result = StringHelper.replaceAll(result, "${" + key.toString() + "}", value);
                    }
                }
                if (intermediateResult.equals(result)) {
                    return result;
                    //throw new Error("Properties value: '" + result + "' migth not point to a valid key.");
                }
            }
        }
        return result;
    }

    public Boolean getPropertyAsBoolean(final String key) {
        String value = getProperty(key);
        return (value.equalsIgnoreCase("true") || value.equalsIgnoreCase("1"));
    }

    public Character getPropertyAsCharacter(final String key) {
        String value = getProperty(key);
        return value.toCharArray()[0];
    }

    public Short getPropertyAsShort(final String key) {
        return Short.parseShort(getProperty(key));
    }

    public Integer getPropertyAsInteger(final String key) {
        return Integer.parseInt(getProperty(key));
    }

    public Long getPropertyAsLong(final String key) {
        return Long.parseLong(getProperty(key));
    }

    public Float getPropertyAsFloat(final String key) {
        return Float.parseFloat(getProperty(key));
    }

    public Double getPropertyAsDouble(final String key) {
        return Double.parseDouble(getProperty(key));
    }
}
